### ISSUE TITLE
WARs in /var/lib/jetty/webapps not picked in Jetty 12 image

### ISSUE THREAD

**Issue by martinleim** [jetty/jetty.docker#172]
### Steps
- Create the the following `Dockerfile`:
  ```
  FROM jetty:12
  ADD --chown=jetty:jetty https://tomcat.apache.org/tomcat-11.0-doc/appdev/sample/sample.war /var/lib/jetty/webapps
  ```
- Build Docker image: `docker build --tag jetty-sample .`
- Run Docker image `docker run jetty-sample`

### Expected result
Jetty is starting with the WAR file is getting deployed.
_Actually, deployment would fail because the Tomcat Sample App is still using `javax` namespace, but I could not find a Jakarta EE sample WAR). Using a JakartaEE 10 WAR I build myself yields the same result._

### Actual result
Jetty starts, no WAR file is getting deployed:
```
/opt/java/openjdk/bin/java -Djava.io.tmpdir=/tmp/jetty -Djetty.home=/usr/local/jetty -Djetty.base=/var/lib/jetty -Djava.io.tmpdir=/tmp/jetty --class-path /var/lib/jetty/resources:/usr/local/jetty/lib/logging/slf4j-api-2.0.9.jar:/usr/local/jetty/lib/logging/jetty-slf4j-impl-12.0.3.jar:/usr/local/jetty/lib/jetty-http-12.0.3.jar:/usr/local/jetty/lib/jetty-server-12.0.3.jar:/usr/local/jetty/lib/jetty-xml-12.0.3.jar:/usr/local/jetty/lib/jetty-util-12.0.3.jar:/usr/local/jetty/lib/jetty-io-12.0.3.jar org.eclipse.jetty.xml.XmlConfiguration java.io.tmpdir=/tmp/jetty java.version=17.0.9 jetty.base=/var/lib/jetty jetty.base.uri=file:///var/lib/jetty jetty.home=/usr/local/jetty jetty.home.uri=file:///usr/local/jetty jetty.webapp.addServerClasses=org.eclipse.jetty.logging.,file:///usr/local/jetty/lib/logging/,org.slf4j. runtime.feature.alpn=true slf4j.version=2.0.9 /usr/local/jetty/etc/jetty-bytebufferpool.xml /usr/local/jetty/etc/jetty-threadpool.xml /usr/local/jetty/etc/jetty.xml /usr/local/jetty/etc/jetty-http.xml
2023-11-03 06:58:08.257:INFO :oejs.Server:main: jetty-12.0.3; built: 2023-10-27T03:25:22.284Z; git: a873259fd5af141dedaa6c7fa8fe8fbdedce0d61; jvm 17.0.9+9
2023-11-03 06:58:08.287:INFO :oejs.AbstractConnector:main: Started ServerConnector@3ee0fea4{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2023-11-03 06:58:08.298:INFO :oejs.Server:main: Started oejs.Server@1176dcec{STARTING}[12.0.3,sto=5000] @408ms
```

### More information
The deployment is started if I use `jetty:11`. Is there a bug in the Docker image? Or has the deployment path changed in Jetty 12 and the documentation is lacking?

**Comment by joakime** [comment]
Unlike Jetty 10 and Jetty 11, which were tied to a specific Jakarta Servlet version, Jetty 12 is a neutral Web Server with no ties to a specific Servlet version.

It can deploy things that have nothing to do with Servlet.
It can also deploy ee10 / ee9 / ee8 versions of webapps all at the same time.

https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-deploy

Deployer | Environment | Servlet #19 | namespace
---- | ---- | ---- | ----
`core-deploy` | n/a (jetty-core only) | n/a (no servlet support) | n/a (no EE# used here)
`ee10-deploy` | ee10 | Servlet 6.0 | `jakarta.servlet.`
`ee9-deploy` | ee9 | Servlet 5.0 | `jakarta.servlet.`
`ee8-deploy` | ee8 | Servlet 4.0 | `javax.servlet.`

The default configuration in this docker image is in the neutral state.
It is up to you to specify which deployer you want (you can even pick multiple deployers if you have multiple webapps)

Eg: `java -jar $JETTY_HOME/start.jar --add-to-start=ee10-deploy`

Also of note, you should also deploy a `<appname>.properties` to indicate which environment that webapp belongs to.

https://eclipse.dev/jetty/documentation/jetty-12/operations-guide/index.html#og-deploy-rules-environment

If you are copying a file named `myapp.war` to the `${JETTY_BASE}/webapps/` directory, and you want it deployed to ee10.
Also include a `myapp.properties` file with 1 line that says `environment=ee10`

Since you stated your webapp is still using `javax` then you should use the `ee8` environment.

**Comment by martinleim** [comment]
The application now deploys if I start the Docker container with `docker run jetty-sample --module=ee8-deploy`. 

Many thanks, @joakime, for the assistance - and for the fact that you did not just write _RTFM_ (which would also have been a valid answer).

**Comment by bodograumann** [comment]
I think this is important information for anyone migrating. If you build your own docker image based on this jetty image, the following enables ee10/v6 servlets:

```
RUN echo "--modules=ee10-deploy" > ${JETTY_BASE}/start.d/ee10-deploy.ini
```

Can we add this information to the docker readme?

**Comment by joakime** [comment]
> Can we add this information to the docker readme?

@lachlan-roberts wdyt?

In Jetty 12, servlet support is now optional.
We've seen a growing number of users using jetty.docker without using servlet, war, webapps, etc.
Perhaps we should just make it clear that servlet / webapp is now optional in Jetty 12?
