### ISSUE TITLE
which: command not found

### ISSUE THREAD

**Issue by bwcxyk** [jetty/jetty.docker#199]
jetty.sh run
`/usr/local/jetty/bin/jetty.sh: line 368: which: command not found`

**Comment by joakime** [comment]
what is the image ID that you used to cause this error?
You can share your `Dockerfile`

**Comment by bwcxyk** [comment]
> what is the image ID that you used to cause this error? You can share your `Dockerfile`

jetty:9.4-jdk8-amazoncorretto

**Comment by joakime** [comment]
Note: Jetty 9, Jetty 10, and Jetty 11 are all now at End of Community Support.

See:

* https://github.com/jetty/jetty.project/issues/7958
* https://github.com/jetty/jetty.project/issues/10485

You should be using Jetty 12.
Since you have old webapps, you can use the `ee8` environment in Jetty 12 to use the old `javax.servlet` namespace.

**Comment by lachlan-roberts** [comment]
The image `amazoncorretto:8` or even `amazoncorretto:21` doesn't have the `which` command installed.

So I think this has little to do with Jetty version and just the fact that amazoncorreto is being used.

@bwcxyk You can install `which` yourself by adding this to your Dockerfile:
```Dockerfile
USER root
RUN yum install which -y
USER jetty
```

**Comment by bwcxyk** [comment]
> ```dockerfile
> USER root
> RUN yum install which -y
> USER jetty
> ```
I'm using the

**Comment by bwcxyk** [comment]
Use
```
java -jar /usr/local/jetty/start.jar
